spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/1911?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver  resources:
    static-locations:
    - classpath:/resources/
  http:    encoding:      force: true      charset: UTF-8      enabled: true  mvc:    view:      prefix: /WEB-INF/
      suffix: .jsp
     
mybatis:  mapper-locations:
  - classpath:mapper/*.xml
  
logging:
  level:
    com.st.dao: debug
   
server:  tomcat:    uri-encoding: UTF-8


